import React from "react";
import Head from "next/head";

import { css } from "@emotion/react";
import styled from "@emotion/styled";

/* // responsible to call the API
  useEffect(async () => {
    try {
      const data = await ipApi.getIp(infoIpSearched);
      setResultIp(data);
    } catch (error) {
      setIsError(true);
    }
  }, [infoIpSearched]); */

const Title = styled.h1(
  ({ theme }) => css`
    font-size: 3.4rem;
    color: ${theme.colors.blak};
  `
);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Boilerplate Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title>Hello World</Title>
      </main>
    </div>
  );
}
